# Generated by Django 4.1.7 on 2023-03-08 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlShortModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('long_url', models.CharField(max_length=400, verbose_name='long_url')),
            ],
        ),
    ]
